from App.Setup.Globals import BLACK, SCREENSIZE, WHITE

BANNER_POSITION = "center", (515, 130)
BANNER_FONTFAMILY = "OpenSans"
BANNER_SIZE = 280, 80
BANNER_FONTSIZE = 40
BANNER_FONTCOLOR = WHITE
BANNER_BGCOLOR = BLACK
BANNER_TEXT = "Introbattle"

GUILDOPTIONS_POSITION = "center", (int(SCREENSIZE[0]/2), int(SCREENSIZE[1]/2))
GUILDOPTIONS_GRID_SPACING = (150, 140)

HEROPORTRAIT_IMAGESIZE = 115, 115
HEROPORTRAIT_LITTLEBOX_SIDE = 10

SELECTOR_DISPLACEMENT = 0, -8
