from App.Setup.Globals import BLACK, SCREENSIZE, WHITE

BANNER_POSITION = "center", (515, 130)
BANNER_FONTFAMILY = "OpenSans"
BANNER_SIZE = 280, 80
BANNER_FONTSIZE = 40
BANNER_FONTCOLOR = WHITE
BANNER_BGCOLOR = BLACK
